<h2>Mention Légale</h2>

<h3>Utilisation de l’information</h3>
<p>Les données exposées dans Pêche Manager sont valables uniquement au niveau informatique. 
  Vous les utilisez sous votre entière responsabilité. Elles n’ont été vérifiées par aucun organisme officiel et 
  ne SONT donc PAS VALABLES POUR LA NAVIGATION. L’équipe de Pêche Manager décline toute responsabilité en cas de préjudices 
  dérivés de l’interprétation et de l’utilisation de l’information fournie sur ce site Web.</p>

<h3>Copyright</h3>
<p>Vous êtes autorisé à imprimer la table à des fins d’utilisation personnelle. 
Il est formellement INTERDIT de copier, reproduire, céder ou rediffuser totalement ou partiellement les graphiques
et les contenus du site Pêche Manager à quelque fin que ce soit et quel que soit le moyen utilisé.</p>

<h3>Information pour les webmasters</h3>
<p>L’information publiée dans Pêche Manager N’EST PAS disponible avec des gadgets ou une technologie similaire;
elle est accessible uniquement au travers de cette adresse Pêche Manager. Nous autorisons tous les utilisateurs d’Internet 
à établir des liens vers l’une des pages de ce site et à utiliser, à quiconque le souhaite, 
l’un de nos logotypes et banners pour relier le site Web.</p>

<h3>Politique de confidentialité</h3>
<p>Nous vous informons que les renseignements fournis au travers du formulaire de contact seront utilisés uniquement 
pour envoyer une réponse à votre consultation, s’il y a lieu. Vous ne recevrez en aucun cas des courriers commerciaux 
et vos données ne seront pas utilisées à des fins autres que celles mentionnées.</p>
